export const RESUME_DATA = {
    name: "Subhankar Pradhan",
    role: "Full Stack Developer",
    experience: "3.3+",
    email: "subhankar.pradhanofficial@gmail.com",
    phone: "+91-9337409100",
    summary: [
        "Accomplished and results-driven professional with a B.Tech, backed by 3.3 years of achievement-oriented experience at Sabado Technologies, Bangalore.",
        "Proficient in React.js frontend development including API integration, secure token/cookie-based authentication, and complex UI rendering.",
        "Experienced in building scalable RESTful APIs using Node.js, Express.js, and Sequelize ORM, with strong expertise in MySQL.",
        "Skilled in deploying and managing applications on AWS using Docker for containerized deployment and cloud automation.",
    ],
    highlights: [
        { label: "Years Experience", value: "3.3+", icon: "⏱" },
        { label: "Projects Delivered", value: "4+", icon: "🚀" },
        { label: "Tech Stack", value: "15+", icon: "⚡" },
        { label: "Team Collaborations", value: "25+", icon: "👥" },
    ],
    skillCategories: [
        {
            category: "Frontend",
            icon: "🎨",
            skills: [
                { name: "React JS", level: 90 },
                { name: "Redux", level: 85 },
                { name: "JavaScript", level: 90 },
                { name: "TypeScript", level: 80 },
                { name: "HTML/CSS", level: 85 },
                { name: "React Native", level: 70 },
            ],
        },
        {
            category: "Backend",
            icon: "⚙️",
            skills: [
                { name: "Node JS", level: 90 },
                { name: "Express JS", level: 90 },
                { name: "Sequelize ORM", level: 85 },
                { name: "REST APIs", level: 90 },
                { name: "JWT & RBAC", level: 85 },
                { name: "Swagger", level: 75 },
            ],
        },
        {
            category: "Database",
            icon: "🗄️",
            skills: [
                { name: "MySQL", level: 90 },
                { name: "MongoDB", level: 70 },
                { name: "Elasticsearch", level: 75 },
                { name: "Redis", level: 70 },
            ],
        },
        {
            category: "DevOps & Tools",
            icon: "☁️",
            skills: [
                { name: "AWS", level: 75 },
                { name: "Docker", level: 80 },
                { name: "Git & GitHub", level: 85 },
                { name: "Linux / Putty", level: 75 },
                { name: "JIRA", level: 80 },
                { name: "Postman", level: 85 },
            ],
        },
    ],
    projects: [
        {
            id: 1,
            title: "HMS",
            subtitle: "Hygiene Management System",
            domain: "Food Service Management",
            teamSize: 4,
            tech: ["Node JS", "React JS", "Python", "MySQL", "Elasticsearch", "Docker"],
            description:
                "Optimizes restaurant performance and market value by conducting comparative analyses with similar establishments through comprehensive market research, menu analysis, and quality assessment.",
            contributions: [
                "Designed and developed responsive React.js screens for Select & Analyze and Reports modules",
                "Implemented Redux for global state management across screens",
                "Developed screen-specific APIs using Node.js with stored procedures",
                "Integrated Swagger for API docs and JWT-based authentication with RBAC",
                "Optimized SQL queries improving application speed significantly",
            ],
            color: "#06b6d4",
        },
        {
            id: 2,
            title: "MyMenu.ai",
            subtitle: "Restaurant Analytics Platform",
            domain: "Restaurant Analytics & SaaS",
            teamSize: 4,
            tech: ["React.js", "Node.js", "MySQL", "ElasticSearch", "Docker", "Postman"],
            description:
                "A pricing intelligence platform that allows restaurant owners to compare menu data with nearby competitors within a 30–50 mile radius, featuring integrated payment gateway for premium data access.",
            contributions: [
                "Designed and implemented end-to-end payment flow from DB schema to frontend",
                "Built secure Express.js APIs for payment validation and access control",
                "Developed MySQL database structure for subscriptions and location-based analytics",
                "Implemented interactive dashboards with dynamic filtering in React.js",
                "Collaborated in Docker-based deployment and API testing",
            ],
            color: "#8b5cf6",
        },
        {
            id: 3,
            title: "RingPe",
            subtitle: "Digital Payments Platform",
            domain: "Banking & Fintech",
            teamSize: 8,
            tech: ["Node JS", "React JS", "React Native", "MySQL", "MongoDB", "Docker"],
            description:
                "Digital payments platform providing BBPS & Wallet-based financial solutions for organizations, supporting water bill and FASTag payments with comprehensive admin panel.",
            contributions: [
                "Developed Node.js backend APIs for allowance allocation and transaction validation",
                "Integrated React.js APIs for seamless frontend-backend communication",
                "Implemented responsive UI components for cross-device experience",
                "Designed dynamic APIs for organization-specific transaction rules",
                "Ensured secure access with JWT authentication and RBAC",
            ],
            color: "#ec4899",
        },
        {
            id: 4,
            title: "BTS",
            subtitle: "Billing Tracking System",
            domain: "Healthcare",
            teamSize: 9,
            tech: ["Node JS", "React JS", "MySQL", "Apache Tomcat", "Postman"],
            description:
                "Healthcare billing management system for tracking and managing billing of healthcare services with a responsive interface for healthcare professionals.",
            contributions: [
                "Developed front-end with React JS and back-end with Node.js",
                "Designed and implemented MySQL database functionalities",
                "Configured and optimized Apache Tomcat for deployment",
                "Conducted thorough testing and debugging for reliability",
                "Participated in code reviews to maintain code quality",
            ],
            color: "#f59e0b",
        },
    ],
    experience: [
        {
            role: "Consultant Full Stack Developer",
            company: "Sabado Technologies",
            location: "Bangalore, Karnataka, India",
            period: "November 2022 – Present",
            highlights: [
                "Building scalable full-stack applications using React.js and Node.js",
                "Implementing secure authentication with JWT and RBAC",
                "Writing optimized SQL queries and stored procedures",
                "Containerized deployments with Docker on AWS",
                "Following Agile methodology with JIRA project management",
            ],
        },
    ],
    education: {
        degree: "B.Tech",
        institution: "Vignan Institute of Technology and Management",
        location: "Berhampur, Odisha, India",
        period: "2018 – 2022",
    },
    certification: {
        title: "Full Stack Development Course",
        institute: "JSpider, Bangalore",
        year: "2022",
        credentialId: "JSP-24-7617",
    },
};